MSUTeam/MSU

- scripts/!mods_preload/msu_mod_item.nut
Added a method for adding itemtypes with names that are then shown below an item's name in the tooltip
> ItemTypeName

- scripts/!mods_preload/msu_class_definitions.nut
- scripts/!mods_preload/msu_throwables.nut
Adds a weighted container to allow modders to easily roll for a random string from a weighted collection.
> Weighted container

- msu/utilities/array.nut
[Rename Array.getRandom to Array.rand](https://github.com/Battle-Brothers-Legends/mod_MSU/commit/5e9fe5f7cf1f7c4acae430b96c01105454854d82)
> Rename Array.getRandom to Array.rand

- msu/systems/mod_settings/button_setting.nut
- msu/systems/mod_settings/load.nut
- msu/systems/mod_settings/mod_settings_system.nut
- msu/test/mod_settings_system_test.nut
- msu/ui/load.nut
- scripts/mods/msu/settings_screen.nut
- ui/mods/msu/css/settings_screen.css
- ui/mods/msu/mod_settings/button_setting.js
- ui/mods/msu/mod_settings/settings_screen.js
Adds a new button setting to which callbacks can be added.
> feat: add "Button" setting type

- msu/utilities/misc.nut
The idea of this PR is to restrict the behavior of the `isIn` function as much as possible to how the default `in` keyword works, while implementing separate functions for BB specific classes to look up their chain of "inheritance".
> Key getting utils

- msu/hooks/skills/skill.nut
- msu/hooks/skills/skill_container.nut
- msu/hooks/states/tactical_state.nut
- msu/hooks/ui/screens/tactical/modules/turn_sequence_bar/turn_sequence_bar.nut
- msu/utilities/skills.nut
The system has been tested in PTR and works fine. If you have suggestions for better naming convention for the public part of the system e.g. `modifyPreviewField` etc. or `onAffordablePreview` function names, please sajest.
> On affordable preview

- msu/load.nut
- msu/msu_mod/load.nut
- msu/msu_mod/msu_mod_debug.nut
- msu/msu_mod/msu_mod_modsettings.nut
- msu/msu_mod/setup_msu_mod.nut
- msu/systems/debug/debug_mod_addon.nut
- msu/systems/debug/debug_system.nut
- msu/systems/empty_mod_addon.nut
- msu/systems/load.nut
- msu/systems/mod.nut
- msu/systems/mod_settings/load.nut
- msu/systems/registry/load.nut
- msu/systems/registry/registry_system.nut
- msu/systems/serialization/load.nut
- msu/vanilla_mod/setup_vanilla_mod.nut
Automatically registers mods when they're created/register with MSU.
I also added two little helper functions to the debug addon to quickly enable/disable debug with the default flag since the constructor parameter is gone.
> Auto register

- msu/msu_mod/msu_mod_modsettings.nut
- msu/systems/keybinds/keybinds_mod_addon.nut
- msu/systems/keybinds/keybinds_system.nut
- msu/systems/mod_settings/abstract_setting.nut
- msu/systems/mod_settings/load.nut
- msu/systems/mod_settings/mod_settings_mod_addon.nut
- msu/systems/mod_settings/settings_divider.nut
- msu/systems/mod_settings/settings_element.nut
- msu/systems/mod_settings/settings_page.nut
- msu/systems/mod_settings/settings_title.nut
- msu/systems/mod_settings/string_setting.nut
- msu/test/mod_settings_system_test.nut
- msu/ui/load.nut
- msu/vanilla_mod/vanilla_keybinds.nut
- ui/mods/msu/css/settings_screen.css
- ui/mods/msu/mod_settings/boolean_setting.js
- ui/mods/msu/mod_settings/button_setting.js
- ui/mods/msu/mod_settings/divider_setting.js
- ui/mods/msu/mod_settings/enum_setting.js
- ui/mods/msu/mod_settings/keybind_setting.js
- ui/mods/msu/mod_settings/range_setting.js
- ui/mods/msu/mod_settings/settings_screen.js
- ui/mods/msu/mod_settings/string_setting.js
- ui/mods/msu/mod_settings/title_setting.js
Improvements to mainly the system addon, the msu modsettings and some settingsElement things
> Modsettings improvements

- ui/mods/msu/css/settings_screen.css
- ui/mods/msu/mod_settings/boolean_setting.js
- ui/mods/msu/mod_settings/button_setting.js
- ui/mods/msu/mod_settings/enum_setting.js
- ui/mods/msu/mod_settings/keybind_setting.js
- ui/mods/msu/mod_settings/range_setting.js
- ui/mods/msu/mod_settings/settings_screen.js
- ui/mods/msu/mod_settings/string_setting.js
- ui/mods/msu/ui_screen.js
It had a lot of duplicate code and was quite franky held together with duct tape
> refactor: improve organisation of CSS and JS

- msu/hooks/states/main_menu_state.nut
- msu/systems/keybinds/keybind_js.nut
- msu/systems/keybinds/keybinds_mod_addon.nut
- msu/systems/keybinds/keybinds_system.nut
- msu/systems/mod_settings/abstract_setting.nut
- msu/systems/mod_settings/elements/boolean_setting.nut
- msu/systems/mod_settings/elements/color_picker_setting.nut
- msu/systems/mod_settings/elements/enum_setting.nut
- msu/systems/mod_settings/elements/range_setting.nut
- msu/systems/mod_settings/elements/string_setting.nut
- msu/systems/mod_settings/load.nut
- msu/systems/mod_settings/mod_settings_mod_addon.nut
- msu/systems/mod_settings/mod_settings_system.nut
- msu/systems/mod_settings/settings_element.nut
- msu/systems/mod_settings/settings_page.nut
- msu/systems/mod_settings/settings_panel.nut
- msu/test/mod_settings_system_test.nut
- scripts/mods/msu/msu_connection.nut
- scripts/mods/msu/settings_screen.nut
- ui/mods/msu/keybinds/keybinds_system.js
- ui/mods/msu/mod_settings/boolean_setting.js
- ui/mods/msu/mod_settings/color_picker_setting.js
- ui/mods/msu/mod_settings/enum_setting.js
- ui/mods/msu/mod_settings/keybind_setting.js
- ui/mods/msu/mod_settings/range_setting.js
- ui/mods/msu/mod_settings/settings_screen.js
- ui/mods/msu/mod_settings/string_setting.js
- ui/mods/msu/msu_connection.js
- ui/mods/msu/utilities.js
Streamline the code and add some qol things.
> Modsettings refactor

- msu/hooks/states/state.nut
- scripts/config/msu/utils.nut
Add state management: keep track of them, provide functions to fetch states
> feat: add state management

- msu/squirrel_hooks/mod_hooks.nut
> feat: allow mods to add custom errors during queue - Close #164

- msu/hooks/items/item_container.nut
- msu/hooks/skills/skill.nut
- msu/hooks/skills/skill_container.nut
The explicit Boolean check (ret == true) is because the vanilla unequip function can return null as well
> feat: add onEquip and onUnquip events for skills

- ui/mods/msu/mod_settings/settings_screen.js
It's fancier than defaulting to the first page
> feat: remember last panel and page and switch to it on show()

- msu/systems/keybinds/keybind_sq_passive.nut
- msu/systems/keybinds/keybinds_mod_addon.nut
- msu/systems/keybinds/keybinds_system.nut
- msu/systems/keybinds/load.nut
> feat: add isKeybindPressed function and passive SQ keybind to keybinds system

- msu/hooks/states/world_state.nut
- msu/systems/serialization/serialization_system.nut
Adds a way to register functions to be executed during world_state hooks to avoid every mod having to hook them separately
> Flag serialization register functions

- msu/systems/mod_settings/mod_settings_mod_addon.nut
- msu/systems/mod_settings/mod_settings_system.nut
- msu/systems/mod_settings/settings_page.nut
- msu/systems/mod_settings/settings_panel.nut
- msu/test/mod_settings_system_test.nut
Mostly I wanted it for the reset button and since I'm a nice guy I made them a separate PR
> feat: add more utility functions to get all settings

- scripts/config/msu/string.nut
For some reason these were initially mixed in with my update checker branch. These are pretty minor QoL functions as much to improve code legibility as for ease of use.
> feat: add startsWith and endsWith functions to ::MSU.String

- scripts/config/msu/text.nut
> Colorize values (Close #162)

- Changelog.md
- msu/msu_mod/msu_mod_modsettings.nut
- msu/msu_mod/msu_tooltips.nut
- msu/systems/mod_settings/mod_settings_mod_addon.nut
- msu/systems/mod_settings/mod_settings_system.nut
- msu/systems/mod_settings/settings_page.nut
- msu/systems/mod_settings/settings_panel.nut
- msu/test/mod_settings_system_test.nut
- scripts/mods/msu/settings_screen.nut
- ui/mods/msu/mod_settings/settings_screen.js
This branch is based on PR #179, so check that one out first
> Modsettings reset functionality

- msu/systems/debug/debug_system.nut
- scripts/config/msu/log.nut
Pretty simple feature that I'd created right after we released 1.1.1 and somehow didn't creat a PR for
> feat: print file, function & line with printData and debug print

- msu/hooks/states/world_state.nut
- msu/systems/serialization/serialization_system.nut
This reverts the addition of registering serialization and deserialization functions (#157). Please confirm if the commit message is acceptable.
> revert: "feat: add method to register functions to be run during..."

- msu/msu_mod/msu_mod_debug.nut
- scripts/config/msu/classes/timer.nut
- ui/mods/msu/utilities.js
This can help time the execution of a specific component more accurately.
> feat: add methods to pause and unpause to SQ and JS timer classes

- msu/vanilla_mod/setup_vanilla_mod.nut
Clears up some minor confusions
> refactor: add (MSU) to name of vanilla settings in modsettings

- ui/mods/msu/css/settings_screen.css
- ui/mods/msu/mod_settings/button_setting.js
> refactor: remove button setting title and move text inside of button

- msu/classes/weighted_container.nut
Allows adding multiple items to the weighted container with the same weight. Returns the container so it can be used as a pseudo-constructor.
> feat: add addMany function

- msu/hooks/ui/screens/tactical/modules/turn_sequence_bar/turn_sequence_bar.nut
> fix: the original JSHandle never being assigned properly

- msu/utils/globals.nut
Adds a deepClone function which should really be in the standard library or at the very least in MSU for a while, this is an old PR that we overlooked and I'd like for it to be included in 1.3 if possible.
> feat: add deepClone function

- msu/hooks/ui/screens/world/modules/world_town_screen/town_travel_dialog_module.nut
> fix(vanilla): not calling onLeave on settlement when using port travel

- msu/systems/persistent_data/persistent_data_mod_addon.nut
- msu/systems/persistent_data/persistent_data_system.nut
- msu/systems/serialization/metadata_emulator.nut
- msu/systems/serialization/serde_emulator.nut
- msu/systems/serialization/serialization_types/abstract_data.nut
- msu/systems/serialization/serialization_types/array_data.nut
- msu/systems/serialization/serialization_types/primitive_data.nut
- msu/systems/serialization/serialization_types/serialization_data.nut
- msu/systems/serialization/serialization_types/table_data.nut
- msu/utils/serialization.nut
this is for consistency with the rest of the codebase. If we're okay with this I thought we should have a PR that we could approve so that if it's fine we can just merge it in.
> refactor: move classes from Serialization.Class to Class
