MSUTeam/MSU

msu/systems/mod_settings/enum_setting.nut
Technically a breaking change, noticed this while working on eimo and it bothered me a lot so I wanna fix it before release. Let me know if you have any issues with it.
=> Make enum_settings have the same param order as other settings

msu/systems/mod_settings/abstract_setting.nut, msu/systems/mod_settings/load.nut, msu/systems/mod_settings/mod_settings_system.nut, msu/systems/mod_settings/settings_element.nut, msu/systems/mod_settings/settings_page.nut, msu/systems/mod_settings/settings_panel.nut, scripts/mods/msu/msu_connection.nut, ui/mods/msu/msu_connection.js, ui/mods/msu/ui_screen.js
In order to have a setting update the JS code when it has a new value set, settings elements are now aware of the panelid of the panel they are in. I tried to think of ways around this but the only one I could think of was making settings not be objects and instead do all the computation within panels which imo isn't really an option anymore.
I'm very open to other suggestions though as I'm not really that happy with this solution.
=> Add mirror of mod-settings in JS code using MSUConnection

msu/hooks/skills/skill_container.nut, msu/utilities/skills.nut
The `_isEmpty` argument is there in case we want to implement a system later on where only those events are called which are present in a skill's nut file. In this case, non-empty functions should be always called and, therefore, it is necessary to know if the event is empty or not.
=> feat: add ability to add skill events via MSU based `addEvent` function

msu/utilities/array.nut
Is this necessary? Having this feature would help for example with cases where you sort based on a function like `getName()`. For example this case in mod_settings_system.nut:
```
function finalize()
{
this.Locked = true;
this.Panels.sort(this.sortPanelsByName);
}
function sortPanelsByName( _key1, _mod1, _key2, _mod2 )
{
return _mod1.getName() <=> _mod2.getName();
}
```
could be replaced with:
```
::MSU.Array.sortAscending(this.Panels, "getName");
```
EDIT: Actually no, because `this.Panels` is OrderedMap, not array. So the example above isn't exactly applicable, but you get the idea.
=> Add handling for function members in sortAscending and sortDescending

msu/utilities/misc.nut
The vanilla BB isKindOf function only works with BB tables. If you pass a WeakTableRef instance to it, it fails. The MSU version handles both.
=> feat: add MSU.isKindOf function which handles both BB tables and WeakTableRef instances

msu/hooks/entity/tactical/actor.nut, msu/hooks/items/item_container.nut
refactor!: remove getTotalArmorStaminaModifier from actor and add a substitute function in item_container
The new function accepts either an array of slots or a single slot. By default it returns the total StaminaModifier of items in all slots. It has built-in handling for items which may not have the getStaminaModifier() function in them.
The rationale behind removing the function from actor and adding to item_container is that StaminaModifier is a purely item property and while perks such as Brawny affect how much stamina the actor loses due to his items, the StaminaModifier of the items remains static. Therefore, keeping this function in the actor is misleading.
=> Close Issue #14

msu/systems/debug/debug_system.nut, msu/systems/empty_mod_addon.nut, msu/systems/keybinds/abstract_keybind.nut, msu/systems/registry/registry_system.nut, msu/utilities/exceptions.nut
This accomplishes two things:
1. Keeps true Exceptions separate from info-containing Error messages.
2. Avoids copy pasting strings, as Error messages are contained in MSU.Error and we only need to edit them at one place if we want to change something.
**PR implementation:**
In this PR, it requires two lines of code wherever you wanna throw an error and exception:
```squirrel
::logError(MSU.Error.ModNotRegistered(_key));
throw ::MSU.Exception.KeyNotFound(_key);
```
**Alternative:**
An alternative method could be to implement a `::MSU.exceptionWithError( _exception, _error = null )` function and use it as follows. The name of this function could be shortened to something like `::MSU.exception` or `::MSU.exEr` etc.
```squirrel
throw …
```
=> MSU.Error and refactor code accordingly

msu/systems/serialization/serialization_mod_addon.nut, msu/systems/serialization/serialization_system.nut
See the code block below for explanation of the use case. If you guys prefer, **we can limit the serialization to only value types** i.e. integer, boolean, string for now until we are confident we wanna add the table/array stuff (because that can lead to issues if it is an array containing BB classes for example). If we implement this, we can simplify the (de)serialize functions of WeightedContainer to use these utility functions. In cases where the **array/table contains mixed value types**, these functions make life even easier. For example **see PR #81** where I have implemented a serialization system for OrderedMap using these utility functions.
```squirrel
function onSerialize( _out )
{
_out.writeU32(this.Array.len());
foreach (item in this.Array)
{
_out.writeU32(item); // if it is …
```
=> Utility functions for Array/Table serialization

msu/classes/weighted_container.nut
As explained in PR #81, shouldn't the `map` function look like this?
```squirrel
function map( _function )
{
// _function (_item, _weight)
local ret = ::MSU.Class.WeightedContainer();
foreach (pair in this.Array)
{
ret.add(_function(pair[1], pair[0]));
}
return ret;
}
```
instead of the current:
```squirrel
function map( _function )
{
// _function (_item, _weight)
return ::MSU.Class.WeightedContainer(clone this.Array).apply(_function);
}
```
=> Weighted container refactor

msu/classes/ordered_map.nut
My main question is about the `map` function. Looking at the description of the `map` function in squirrel documentation it says:
> This method applies the supplied function to every item in the target array, one by one. The results are placed in a new array created by map() and returned by it. The new array will be the same size as the target array.
Contrast map() with [apply()](https://developer.electricimp.com/squirrel/array/apply) which changes the array’s items in situ.
The passed function must include a single parameter into which each item in the target array is passed. It is the function’s job to make sure the array values passed are appropriate to the changes it will make, if any.
and
> Creates a new array of the same size. For each element in the original array invokes the …
=> Ordered map tweaks

msu/classes/weighted_container.nut
This helps to improve performance, while also allowing a `foreach (item, weight in container)` type iteration loop. It also gets rid of the ApplyIdx which was a potential pitfall for certain iteration cases.
=> Change WeightedContainer to use a Table internally

scripts/config/msu/semver.nut
Making a PR here because I haven't really used this approach where we have 1 shared verification function so wanna make sure it's fine with everyone.
=> fix: SemVer compare functions not accepting mod objects

msu/hooks/states/world_state.nut
I've kept in the code for handling pre 1.1 saves so nothing will change when loading them, the new info will only be shown when loading a 1.1+ save.
=> feat: add the ability to detect missing (hooks) mods in log

scripts/config/msu/type_checkers.nut
I believe using `format` here has a chance of failure because as we saw earlier in the `getInQuotes` function, format doesn't seem to roll nicely with stuff that can't be converted to string? So we should instead use string concatenation here, right?
=> feat: add helpful log errors to type checking functions

scripts/config/msu/table.nut
This fixes the issue where it was only checking for one value being table instead of both. This `_recursively` thing was added by @Enduriel and personally I still don't know if it should be included at all. The function is supposed to be an analogy to `array.extend` and that function doesn't do recursive extension either. What do you guys think?
=> fix: add check that the values in both tables are tables instead of only in one table

msu/hooks/skills/skill.nut
This allows modders to do the following in a skill file:
```squirrel
this.m.AIBehavior = {
ID = ::Const.AI.Behavior.ID.PTRArrowToTheKnee,
Script = "scripts/ai/tactical/behaviors/ai_ptr_arrow_to_the_knee"
};
```
instead of:
```squirrel
function onAdded()
{
if (!this.getContainer().getActor().isPlayerControlled() && this.getContainer().getActor().getAIAgent().findBehavior(::Const.AI.Behavior.ID.PTRArrowToTheKnee) == null)
{
this.getContainer().getActor().getAIAgent().addBehavior(this.new("scripts/ai/tactical/behaviors/ai_ptr_arrow_to_the_knee"));
this.getContainer().getActor().getAIAgent().finalizeBehaviors();
}
}
```
or when hooking a file, even worse:
```squirrel
::mods_hookNewObject("skills/actives/aimed_shot", function(o) {
local onAdded = ::mods_getMember(o, "onAdded"); …
```
=> feat: add ability to specify AI behavior that will be added when a skill is added

msu/hooks/items/weapons/weapon.nut
I tested this fix ingame for a weapon.
Now you are able to have a Weapon with no weapontype (just one-handed or two-handed by themselves)
But more importantly: The game doesn't crash anymore if someone removes the last type of an item even if they give it another type right after.
Closes #211
=> fix: add check to prevent slice on empty string

msu/hooks/skills/skill.nut, msu/hooks/skills/skill_container.nut, msu/hooks/ui/screens/tooltip/tooltip_events.nut
Adds an event to skills that allows skills to modify the tile tooltip before it is displayed to keep such modifications nicely compartmentalized within skills (similar to onGetHitFactors and onQueryTooltip functions).
=> feat: add onQueryTileTooltip event for skills

msu/msu_mod/load.nut, msu/msu_mod/msu_keybinds.nut, scripts/mods/msu/popup.nut, ui/mods/msu/popup.js
This currently instead closes the game in the main menu if a popup appears, which is really annoying.
This also required the handling of `Animating` and `Visible` for popup, this code has effectively been cloned from `ui_screen.nut`
=> feat: add keybind to close popup when clicking escape

msu/hooks/entity/tactical/actor.nut, msu/hooks/skills/skill.nut, msu/hooks/skills/skill_container.nut
This adds an event that is called at the end of `update()` after the `CurrentProperties` of the actor have been completely set up by the `update` function. It allows us to do things like the following:
```squirrel
// In some skill that is supposed to expire if the actor gets stunned
function onSkillsUpdated()
{
if (this.getContainer().getActor().getCurrentProperties().IsStunned) this.removeSelf();
}
```
The above is currently impossible to do without hard coding like vanilla. Vanilla does it by using the `onAdded` function of the `Stunned` effect and any other effects e.g. `Horrified` that cause the character to be stunned and in that function they manually enter the ids of the skills that should be removed e.g. `effects.riposte`, `effects.spearwall` etc. This is very tightly coupled and …
=> feat: add onSkillsUpdated event for skills

scripts/config/msu/classes/enum.nut
The goal here is to simplify the creation of an extensible enum.
Squirrel Enums are not extensible by design, and BB Enums don't have any of the convenience functions that would allow modders to easily add their own values (or any of the safety checks to make sure values are ordered).
Imo we might wanna add a second Enum Class that handles enums with arbitrary values that can be defined by the modder. I'd initially made it be just a toggle set during the instantiation, but that overcomplicated some of the aspects of the class. It also shouldn't be a child/parent class of this, but maybe they can both inherit from the same abstract ancestor. I think we can leave it for now and get to it at a later point.
=> feat: adds an enum class

msu/hooks/ui/screens/tooltip/tooltip_events.nut
This fixes the issues caused by these functions having been updated in vanilla since the time the original hook in MSU was written leading to wrong behavior. This new method is less efficient as it calls getEntityById and getSkillByID while these things are also called by the vanilla functions, but this implementation is more robust against vanilla updates to these functions.
=> fix: refactor the query tooltip functions to include a call to the base vanilla function instead of complete overwrite

scripts/config/msu/utils.nut
This reverts commit b6e45896b716120fc69dbdddf3ef9bd496af692c. A function with this functionality was added to ::MSU.AI namespace instead in #203.
=> feat: deprecate MSU.Utils.addAIBehaviour

scripts/config/msu/table.nut
This makes it more convenient to use, for example with clone().
=> feat: return first passed table of ::MSU.Table.merge()

msu/systems/mod_settings/abstract_setting.nut
With the new reset() functionality, this is a much cleaner way of achieving the same thing. This function was undocumented, so it can be a breaking change.
=> Simplify setBaseValue function

msu/systems/mod_settings/abstract_setting.nut, msu/systems/mod_settings/elements/boolean_setting.nut, msu/systems/mod_settings/elements/button_setting.nut, msu/systems/mod_settings/elements/string_setting.nut
Originally, the callbacks ran before the value was changed, passing the new value.  This was not very convenient in practice. With this PR, the user can decide whether to run the callback before or after a change. The new value gets passed in BeforeChange callbacks, the old value in AfterChange callbacks.
=> Split Settings callback into callbacks for Before and After the value was changed

msu/hooks/states/root_state.nut, msu/systems/keybinds/abstract_keybind.nut, msu/systems/keybinds/keybinds_mod_addon.nut, msu/systems/keybinds/keybinds_system.nut, msu/systems/mod_settings/elements/keybind_setting.nut
This depends on #235 .
This simplifies some aspects of the Keybinds system by making the Modsettings system entirely responsible for setting values, while they are only fetched directly from the setting. Persistent data is now also handled entirely over Modsettings. Concerns are further separated and the code is easier to read and maintain.
=> Simplify keybind settings by offloading the actual settings functionality to the modsettings system

msu/hooks/states/world_state.nut, msu/systems/mod_settings/abstract_setting.nut, msu/systems/mod_settings/elements/enum_setting.nut, msu/systems/mod_settings/mod_settings_system.nut, msu/systems/mod_settings/settings_panel.nut
currently requires that the local version is bumped up to 1.2.0, and will not load properly otherwise.
Now that we have a standardized implementation of flagSerialization, this commit removes the old custom setup for ModSettings, and instead makes the system rely on the Serialization System's new additions
=> refactor: move mod settings serialization to serialization system

msu/hooks/load.nut, msu/hooks/root_state.nut, msu/hooks/skills/skill.nut, scripts/config/msu/ai.nut
This is accomplished via a hook on root_state onInit function that populates an ID to Script file name map. This way we don't need the user to pass both the id and the script file name for the behavior.
=> feat: use behavior ID only

msu/hooks/ai/tactical/agent.nut, msu/hooks/skills/skill.nut
This is dependent on the changes from #244 and basically allows us to safely remove the behavior added by a skill if that skill is removed. It is far simpler than the skills thing because we don't have to care about any references or items or anything.
=> Stack based behavior addition removal

msu/systems/serialization/serialization_system.nut, msu/utils/utils.nut
This `Utils.deserialize` function should not change the values of any object - as this violates the single responsibility principle. It should take a metadata object and deserialize an object from it and return the deserialized object.
=> Segregate deserialize functions scope

msu/systems/mod_settings/abstract_setting.nut, msu/systems/serialization/deserialization_emulator.nut, msu/systems/serialization/serde_emulator.nut, msu/systems/serialization/serialization_emulator.nut, msu/systems/serialization/serialization_mod_addon.nut, msu/systems/serialization/serialization_system.nut
serialization of BB objects is now handled by passing a Serialization or Deserialization Emulator to them.
Normal deserialiation now requires a default value.
SerDeEmulators are now permanently linked to a FlagContainer they are assigned during instantiation.
SerializationEmulators now have an Incremental mode where they store their data in the flag container as soon as something is written to them.
DeserializationEmulators now immediately clear flags from their FlagContainer as they deserialize.
SerDeEmulator flag IDs are validated to make sure they do not collide with flags generated by other emulators.
=> fix: flagSerialization edge case errors

msu/systems/mod_settings/mod_settings_mod_addon.nut
This reverts commit 438ac6fb918c54b74acd105381f2a059563a419a.
We've decided to remove `requireSettingValue` for now and we'll do a better implementation of the entire concept in a future version.
=> revert: "feat: add requireSettingValue function"

msu/hooks/skills/skill.nut
This is important because we add behavior by stack. And if we check for pre-existing behavior, then we don't add the behavior but we still remove it when the skill is removed. This leads to issues when a skill removes itself upon execution e.g. Throw Spear or Throw Net which get removed due to the item being one-use only. As this happens mid-execution of an ai behavior, the behavior is removed and the game freezing as the behavior is no longer attached to an actor.
=> fix: remove check for existing behavior

msu/hooks/skills/skill.nut
These are pulled 1:1 from msu item.nut as Skill Type and Item Type function the same way.
=> feat: add Type mutator and accessor functions to skill.nut

msu/hooks/ai/tactical/agent.nut, msu/hooks/skills/skill.nut
This fixes issues when a skill is used which removes itself upon execution, leading to the skill removing its behavior mid-execution of the behavior, which leads to errors and combat freeze. With this commit, we check if the removed skill's behavior is the currently active behavior, and if yes, then only remove it after the execution is complete.
=> fix: remove active behavior only after execution is complete

msu/hooks/items/weapons/weapon.nut
Because an update already happens during addSkill, the AdditionalAccuracy of vanilla skills (e.g. Quick Shot) is set to that of the item due to the vanilla onAfterUpdate function of Quick Shot which sets its AdditionalAccuracy to that of the item. Then we added the item's accuracy to it again and then saved that as the base value. This led to doubling the AdditionalAccuracy in the skill. By resetting it before adding the item's we ensure that the item's AdditionalAccuracy is added to the base value of the skill that it had before the update loop.
=> fix: reset AdditionalAccuracy of skill before adding item's to it

msu/hooks/items/item_container.nut
This is more robust against the addition of other item slots in the future, as we no longer have to worry about which ItemSlot keys to keep and which to delete. The indices of the ItemSlotSpaces array will always align with the ItemSlots which are actually usable.
See the following report from Darxo on Discord which highlights a problem with the current implementation: https://discord.com/channels/965324395851694140/1083975573707161610/1083975573707161610
=> refactor: use ItemSlotSpaces instead of ItemSlot

msu/utils/text.nut
Based on [this feedback](https://discord.com/channels/965324395851694140/1060326291238305853/1073422634425008270). The idea is that `PositiveValue` and `NegativeValue` colors should be moddable, so that if a mod wants to show positive values in some color other than green, it can.
=> Feature color positive color negative

msu/hooks/entity/tactical/tactical_entity_manager.nut
Because `getAllInstancesAsArray` iterates over all instances and pushes them to a new array and returns that. That leads to this function causing 2x iteration over all actors. The new method iterates only once.
=> perf: use getAllInstances instead of getAllInstancesAsArray

msu/hooks/entity/tactical/actor.nut
In vanilla there is no good way to check if a character is disarmed except by checking for `effects.disarmed` effect. However, if a mod adds another way to apply the disarmed status to a character, then other mods won't be able to check for that. This function allows a centralized isDisarmed function that mods can hook to add their checks into it.
=> feat: add isDisarmed function

msu/utils/tile.nut
The utility of the `getNeighbors` function is obvious. The utility of the `getNeighbor` function is shown below:
```squirrel
// Objective:
// Get the first empty tile adjacent to myTile
// current workflow
local targetTile;
for (local i = 0; i < 6; i++)
{
if (myTile.hasNextTile(i))
{
local nextTile = myTile.getNextTile(i);
if (nextTile.IsEmpty)
{
targetTile = nextTile;
break;
}
}
}
// new workflow:
local targetTile = ::MSU.Tile.getNeighbor(myTile, @(tile) tile.IsEmpty);
```
=> feat: add functions to get neighboring tiles

msu/hooks/items/item_container.nut
To be merged AFTER #316 (port to modern hooks)
=> feat: add getItemsByFunction and getItemsByFunctionAtSlot

msu/utils/globals.nut
Because it is redundant with the instanceof check.
=> perf: remove check for typeof instance

msu/systems/system.nut, msu/utils/globals.nut, msu/utils/type_checkers.nut
Sorry I really should've done this with the recent #350 but after having merged that I realized I should do a sweep of this thing in the entire codebase and found a few more occurrences that can be improved. Hence this PR.
=> perf: remove redundant typeof instance check from various functions

msu/hooks/items/item_container.nut
As discussed on Discord. We added these features in #323 ahead of the release of 1.3.0 but are removing them before the release.
This reverts commit b3b8ab6ca81f87bf918277f983b404266b1e4467.
Because the functionality added by these functions can be achieved natively by using `.filter` on vanilla `getAllItems` and `getAllItemsAtSlot` functions of item_container.
=> revert: "feat: add getItemsByFunction and getItemsByFunctionAtSlot (#323)"

msu/utils/tile.nut
As per discussion on Discord. These features which were added for the 1.3.0 build before release are being changed. Reasoning 
being:
1. Remove `_function` because the native `filter` can be used on the returned array. And performance isn't a concern.
2. Remove `getNeighbor` as it was returning the first valid neighbor. But that can be achieved in other ways and is a niche application.
3. Remove `getRandomNeighbor` as that can simply be achieved via `::MSU.Array.rand` on `getNeighbors`.
=> Refactor tile getNeighbor functions

msu/hooks/skills/skill.nut
This wasn't really causing any issues currently because the scheduled changes are cleared the first time they are run, but for complete sanity this check should be baked in.
=> fix: potentially pushing a skill multiple times for scheduled changes

msu/hooks/ui/screens/tactical/modules/turn_sequence_bar/turn_sequence_bar.nut
The entire point of the switcheroo on JSHandle is so that the original function is called before our skill container event (onAffordablePreview) so that the values set by the original function happen before our event.
This is how it should have been in #313 and how it was in the first implementation of that PR. But in all the refactors switching to switcherooing the JSHandle, it got messed up. Here it is fixed now.
=> fix: costs preview not calling the original early enough

scripts/config/!msu.nut
Annoying, but better than having to deal with an incompatible legends version.
=> refactor: add back VanillaID due to legends using it

msu/utils/globals.nut
I'd like this in 1.3 because
- we need something like this just like deepClone and it's a little embarrassing we don't have it
- it would make doc a lot easier to write when talking about comparing reserialized data
=> feat: add deepEquals function

msu/utils/globals.nut
- For the table case add check for key existing in _b.
- For the instance case require that the class of both instances is the same.
=> fix: table and class cases in deepEquals

msu/hooks/items/weapons/weapon.nut
Also rename relevant functions to be more clear about their intended use case.
=> fix: weapontype being wiped for weapons without categories

msu/systems/serialization/serde_emulator.nut
This is to help diagnose the log spam we are getting from some people
=> refactor: temporarily print full stack trace when deserialization errors

msu/utils/math.nut
Should we call it `round` or something else e.g. `roundToMultiple` or `roundToNearest`?
=> feat: add round function in math utilities to round to nearest multiple

msu/utils/skills.nut
- Handling for null defparam is a bugfix and should be added.
- Other ref-type params are something we can't deal with (without adding a custom wrapper with vargv, which I don't want to do here) so we simply disallow the usage of this function to add those kinds of functions. They can be added by modders in the old school manual way to add skill events.
=> Fix handling for ref type defparams in addEvent skills function

msu/classes/weighted_container_damage_type.nut, msu/hooks/skills/skill.nut
Add a new class for DamageType that extends WeightedContainer and overwrites all functions to first initialize the DamageType of the skill before returning the base function. This ensures that hooks on the skill's create function before hookTree that try to add/remove a DamageType or try to access any other value related to the skill's DamageType do not break the auto-assigning of DamageTypes for skills that don't come with DamageType defined (e.g. vanilla skills).
=> fix: handling for accessing skill DamageType before hookTree

msu/classes/weighted_container_damage_type.nut
Originally we calculated approximate ratios for these "mixed" damage type skills based on the number of injuries there are in vanilla and hard-coded them as weights in the containers so that the injury inflicting behavior with MSU damage type system corresponds to the probability of injuries in vanilla. However, mods may change the number of different types of injuries, causing this ratio to no longer represent the new ratio of injuries. This PR ensures that the ratio is calculated dynamically.
I have used the MSU.Math.roundToMult function #358 to round it to the nearest multiple of 5. For the case of vanilla this only affects `BluntAndPiercing` which in vanilla was giving a ratio of 58/42 but we had it set at 45/55. The others were already exact at multiples of 5. I believe rounded to …
=> feat: auto calculate DamageType ratio in skills

msu/hooks/items/weapons/weapon.nut, msu/hooks/skills/skill.nut
If the actor has a skill which modifies the weapon skills' FatigueCost field in e.g. onAfterUpdate function. This was happening because an update cycle happened during the call to the original `addSkill`, which also calls setFatigueCost and our hook on `setFatigueCost` was also setting the base value to the given cost. The latter is bad from a principle pov too because setting a skill's FatigueCost shouldn't modify its base fatigue cost.
=> fix: FatigueCost getting wrong base value during equipping weapon

msu/msu_mod/msu_mod_modsettings.nut, msu/ui/load.nut, scripts/mods/msu/msu_connection.nut, ui/mods/msu/css/misc.css, ui/mods/msu/css/vanilla_font_unbold.css, ui/mods/msu/msu_connection.js, ui/mods/msu/ui_hooks/xbbcode.js
Went for a different approach with this one which is imo cleaner, previously only text bolded using bbcode would be unbolded, but it turns out vanilla actually bolds some text directly with JS, this is able to handle all those cases. I had to exclude title fonts as those are always bold.
=> fix: vanilla bb code toggle not applying to text bolded using JS

msu/hooks/config/character_injuries.nut
Contains two fixes:
- fix: excluded injuries `get` function extending array by reference
- fix: excluded injuries `get` not including extra injuries of included ones
=> fix: excluded injuries get function extending array by reference

msu/msu_mod/load.nut, msu/systems/debug/debug_mod_addon.nut, msu/systems/debug/load.nut, msu/systems/keybinds/load.nut, msu/systems/mod_settings/load.nut, msu/systems/persistent_data/load.nut, msu/systems/registry/load.nut, msu/systems/registry/mod_sources/mod_source_github.nut, msu/systems/registry/mod_sources/mod_source_nexusmods.nut, msu/systems/serialization/load.nut, msu/systems/tooltips/load.nut, msu/vanilla_mod/load.nut
So that MSU modules outside the MSU zip which are trying to add or modify classes in these folders are able to do that before the classes are instantiated.
=> refactor: streamline certain load files to include entire folders

msu/utils/array.nut
This function removes given values from an array in place as opposed to the native filter function that returns a new array. Doing `_values.find` is expected to be faster than first converting `_values` to a local table and then using `in` for each element in `_array`. This is because looking up values that don't exist in a table is a slower operation than using `find` on an array especially at smaller len - which `_values` is expected to have.
=> feat: add removeValues function to array utilities

msu/utils/utils.nut
This is a useful function for benchmarking a single function or comparing the benchmarks of several functions. Usage:
```squirrel
// Let's say we have 3 functions called foo, bar, baz
// we pass them as references in an array and assign them an id that will be printed in log
::MSU.Utils.benchmark([
["Endy",  foo],
["Midas", bar],
["Taro", baz]
]);
```
This will print to log the performance of the 3 functions as well as their relative performance to the first function i.e. in this case `Endy`.
In case your functions need parameters you can manually call them via passing lambdas to the utility function and using local variables as the args:
```squirrel
::MSU.Utils.benchmark([
["Endy",  @() foo(pass args here)],
["Midas", @() bar(pass args here)],
["Taro", @() baz(pass args here)]
]);
``` …
=> feat: add utility function for benchmarking

msu/systems/registry/load.nut, msu/systems/registry/mod_sources/mod_source.nut, msu/systems/registry/mod_sources/mod_source_github.nut, msu/systems/registry/mod_sources/mod_source_githubtags.nut, msu/systems/registry/mod_sources/mod_source_nexusmods.nut, msu/systems/registry/registry_mod_addon.nut, msu/systems/registry/registry_system.nut, ui/mods/msu/css/popup.css, ui/mods/msu/msu_connection.js
Usage:
```squirrel
mod.Mod.Registry.addModSource(
::MSU.System.Registry.ModSourceDomain.GitHubTags,
// A link into a subdir here, but repo itself is also allowed
"https://github.com/Suor/battle-brothers-mods/tree/master/autopilot"
// tag prefix, for i.e. tag autopilot-new-2.2.0 be 2.2.0 release
{Prefix = "autopilot-new-"});
mod.Mod.Registry.setUpdateSource(::MSU.System.Registry.ModSourceDomain.GitHubTags);
// Can still add this for icon with a link
mod.Mod.Registry.addModSource(
::MSU.System.Registry.ModSourceDomain.NexusMods,
"https://www.nexusmods.com/battlebrothers/mods/675");
```
=> Add GithubTags mod source
